name: hermit
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: '>=2.9.0-20 <3.0.0'

dependencies:
  characters: 1.0.0
  collection: 1.14.13
  meta: 1.1.8
  typed_data: 1.2.0
  vector_math: 2.0.8

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
